"""Add constraint in stocklevel

Revision ID: 8d9ac6f4d796
Revises: 698c79afb687
Create Date: 2026-06-16 16:21:22.288164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9ac6f4d796'
down_revision: Union[str, Sequence[str], None] = '698c79afb687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stocklevel', ['product_id', 'warehouse_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocklevel', type_='unique')
    # ### end Alembic commands ###
