"""update table transfertline checkconstraint

Revision ID: 9651ac511972
Revises: 8d9ac6f4d796
Create Date: 2026-06-16 20:12:18.570213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9651ac511972'
down_revision: Union[str, Sequence[str], None] = '8d9ac6f4d796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'transfertline', ['transfer_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfertline', type_='unique')
    # ### end Alembic commands ###
